apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gscan-secret
  namespace: default
spec:
  encryptedData: {}
  template:
    metadata:
      creationTimestamp: null
      name: gscan-secret
      namespace: default
